Verify signatures on Release and Sources files. Does not verify packages themselves, yet.

diff --git a/package-importer b/package-importer
--- a/package-importer
+++ b/package-importer
@@ -1,4 +1,5 @@
 #!/bin/bash
+set -e
 
 # checks if any imports should be performed and performs them
 # accepts branch with package lists as command-line parameter
@@ -11,8 +12,6 @@
 export BZR_BRANCH_PREFIX=${BZR_BRANCH_PREFIX:-'lp:~elementary-os/ubuntu-package-imports/'}
 export BASE_TMP_DIR=${BASE_TMP_DIR:-"$(pwd)"}
 
-set -e
-
 if [ -z "$@" ]; then
     LISTS_BRANCH="lp:~elementary-os/ubuntu-package-imports/elementary-import-lists"
 else
@@ -20,7 +19,7 @@ else
 fi
 
 # check for dependencies
-dependency_list='devscripts dpkg-dev build-essential bzr quilt lsb-release'
+dependency_list='devscripts dpkg-dev build-essential bzr quilt lsb-release ubuntu-keyring'
 for package in $dependency_list; do
     dpkg -L "$package" >/dev/null 2>&1 || missing_dependencies="$missing_dependencies $package"
 done
@@ -126,6 +125,26 @@ for distro_version in $(ls -1 "$tmp_dir/import-lists"); do
     | tr -d '\n' )
 
     apt-get $apt_options update
+
+    # verify signatures on the Release files so we can verify source code integrity later on
+    echo "Verifying signatures of *_Release files"
+    release_files=$(echo apt_state/lists/*_Release)
+    for release_file in $release_files; do
+        if ! gpg --keyring /etc/apt/trusted.gpg --verify "$release_file.gpg" "$release_file"; then
+            echo "Could not verify signature on $release_file" > /dev/stderr 
+            exit 1
+    done
+
+    # having verified Release files, verify Sources files based on Release files
+    echo "Verifying hashes of *_Sources files"
+    sources_files=$(echo apt_state/lists/*_Sources)
+    for sources_file in $sources_files; do
+        sources_file_hash=$(sha256sum "$sources_file" | cut --only-delimited -d ' ' -f 1)
+        sources_file_size=$(stat --format='%s' "$sources_file")
+        sources_file_server_filename=$(echo "$sources_file" | cut -d '_' -f '6-' | tr '_' '/')
+        corresponding_release_file=$(echo "$sources_file" | cut -d '_' -f '-5')_Release
+        grep -E -m 1 "^[[:blank:]]*$sources_file_hash[[:blank:]]*$sources_file_size[[:blank:]]*$sources_file_server_filename$" "$corresponding_release_file"
+    done
 
     # per-package cycle
     for package in $package_list; do
