replaced bzr branch with bzr checkout --lightweight, should require less network traffic now

diff --git a/package-importer b/package-importer
--- a/package-importer
+++ b/package-importer
@@ -21,7 +21,7 @@ if [ -z "$@" ]; then
     echo "No packages specificed on command line.
 Using package list from $LISTS_BRANCH" > /dev/stderr 
     rm -r "$target_folder"
-    bzr branch "$LISTS_BRANCH"
+    bzr ckeckout --lightweight "$LISTS_BRANCH"
     package_list="$(cat $target_folder/packages_to_import)"
 else
     package_list="$@"
@@ -56,7 +56,7 @@ package_version_already_imported() {
 package="$1"
 version="$2"
 rm -r "$package-$distro_version"
-bzr branch "$bzr_branch_prefix""$package-$distro_version" &&
+bzr ckeckout --lightweight "$bzr_branch_prefix""$package-$distro_version" &&
 grep --silent "$version" "$package-$distro_version"/debian/changelog
 }
 
@@ -78,13 +78,18 @@ https://bugs.launchpad.net/ubuntu-package-imports/+filebug" > /dev/stderr
             exit 1
 }
 
-        if bzr branch "$bzr_branch_prefix""$package-$distro_version" ../"$package-$distro_version"; then
-            # branching succeeded
+        if bzr ckeckout --lightweight "$bzr_branch_prefix""$package-$distro_version" ../"$package-$distro_version"; then
+            # checkout succeeded
             cp -r ../"$package-$distro_version"/.bzr .bzr
             bzr add
-            debcommit
+            debcommit || {
+                echo "Failed to commit the changes or upload the code to the bazaar branch.
+Either your internet connection suddently went out, or it's caused by a bug.
+If your internet connection works, please report this failure at:
+https://bugs.launchpad.net/ubuntu-package-imports/+filebug" > /dev/stderr
+                exit 1
         else
-            # branching failed; assuming the branch doesn't exist, which means
+            # checkout failed; assuming the branch doesn't exist, which means
             # this is the first import of this package
             bzr init
             bzr add
