Updated to version 2.02-2ubuntu8.10

diff --git a/debian/grub-check-signatures b/debian/grub-check-signatures
--- a/debian/grub-check-signatures
+++ b/debian/grub-check-signatures
@@ -8,6 +8,7 @@ set -e
 efivars=/sys/firmware/efi/efivars
 secureboot_var=SecureBoot-8be4df61-93ca-11d2-aa0d-00e098032b8c
 moksbstatert_var=MokSBStateRT-605dab50-e046-4300-abb6-3dd810dd8b23
+tmpdir=$(mktemp -d)
 
 on_secure_boot() {
 	# Validate any queued actions before we go try to do them.
@@ -38,13 +39,44 @@ on_secure_boot() {
 	return 0
 }
 
+# Retrieve the keys we do trust from PK, DB, KEK, and MokList.
+extract_known_keys() {
+	# Make the Canonical CA cert available for validation too; in case
+	# MokListRT is empty due to a bug.
+	cp /usr/share/grub/canonical-uefi-ca.crt $tmpdir
+
+	# Extract known UEFI certs from firmware variables
+	( cd $tmpdir; \
+		mokutil --export --db; \
+		mokutil --export --mok >/dev/null 2>/dev/null; \
+		for derfile in *.der; do \
+			openssl x509 -inform der -in $derfile -outform pem -out $derfile.crt; \
+		done )
+}
+
 # Check if a given kernel image is signed
 is_signed() {
 	tmp=$(mktemp)
-	sbattach --detach $tmp $1 >/dev/null  	# that's ugly...
+	sbattach --detach $tmp $1 >/dev/null 2>/dev/null 	# that's ugly...
 	test "$(wc -c < $tmp)" -ge 16	# Just _some_ minimum size
 	result=$?
+	if [ $result -eq 0 ]; then
+		sig_subject=$(openssl pkcs7 -inform der -in $tmp -print_certs | openssl x509 -noout -text | grep Subject: )
+	fi
 	rm $tmp
+	if [ $result -eq 0 ]; then
+		for crtfile in $tmpdir/*.crt; do
+			sbverify --cert $crtfile $1 >/dev/null 2>/dev/null
+			result=$?
+			if [ $result -eq 0 ]; then
+				return $result;
+			fi
+		done
+		echo "$1 is signed, but using an unknown key:" >&2
+		echo "$sig_subject" >&2
+	else
+		echo "$1 is unsigned." >&2
+	fi
 	return $result
 }
 
@@ -71,7 +103,7 @@ find_unsigned() {
 
 # Only reached from show_warning
 error() {
-	echo "E: Your kernels are unsigned. This system will fail to boot in a secure boot environment." >&2
+	echo "E: Your kernels are not signed with a key known to your firmware. This system will fail to boot in a Secure Boot environment." >&2
 	exit 1
 }
 
@@ -90,8 +122,10 @@ show_warning() {
 }
 
 if on_secure_boot; then
+	extract_known_keys
 	unsigned="$(find_unsigned)"
 	if [ -n "$unsigned" ]; then
 		show_warning "$unsigned"
 	fi
+	rm -rf "$tmpdir"
 fi
