Updated to version 18.04.14.17

diff --git a/scripts/simple-plugins b/scripts/simple-plugins
--- a/scripts/simple-plugins
+++ b/scripts/simple-plugins
@@ -8,8 +8,8 @@ if [ "$1" = "prepare" ]; then
     if [ "$RET" = "true" ]; then
         env -u DEBIAN_HAS_FRONTEND -u DEBCONF_REDIR \
             DEBCONF_DB_REPLACE=configdb DEBCONF_DB_OVERRIDE="Pipe{infd:none outfd:none}" \
-            ubuntu-drivers autoinstall --package-list /run/ubuntu-drivers.autoinstall || \
-		logger -t ubiquity "ubuntu-drivers autoinstall failed with code: $?"
+            ubuntu-drivers install --package-list /run/ubuntu-drivers.autoinstall || \
+		logger -t ubiquity "ubuntu-drivers install failed with code: $?"
     fi
     db_input high ubiquity/secureboot_key || true
     db_get ubiquity/secureboot_key
