Updated to version 18.04.14.14

diff --git a/d-i/source/flash-kernel/functions b/d-i/source/flash-kernel/functions
--- a/d-i/source/flash-kernel/functions
+++ b/d-i/source/flash-kernel/functions
@@ -21,6 +21,7 @@
 
 BOOTSCRIPTS_DIR="${FK_CHECKOUT:-/etc/flash-kernel}/bootscript"
 FK_ETC_MACHINE="${FK_ETC_MACHINE:-/etc/flash-kernel/machine}"
+FK_DEFAULTS="${FK_DEFAULTS:-/etc/default/flash-kernel}"
 PROC_CPUINFO="${FK_PROC_CPUINFO:-/proc/cpuinfo}"
 PROC_DTMODEL="${FK_PROC_DTMODEL:-/proc/device-tree/model}"
 PROC_MTD="/proc/mtd"
@@ -248,21 +249,15 @@ get_dtb_name() {
 			error "dtb-probe $dtb_script failed"
 		fi
 		;;
-	/*)
-		dtb_name="$field"
-		;;
 	*)
-		# DTBs on arm64 are stored in subdirs for each vendor; strip
-		# the dir away (in case someone specified it, although it's
-		# not needed).
-		# The DTB will be stored in /boot/dtbs/$kvers/ without
-		# additional subdirs.
-		dtb_name=$(basename "$field")
+		dtb_name="$field"
 		;;
 	esac
 	if [ -n "$dtb_name" ] ; then
 		echo "Using DTB: $dtb_name" >&2
 	fi
+	dtb_dir=$(dirname "$dtb_name")
+	dtb_name=$(basename "$dtb_name")
 }
 
 machine_uses_flash() {
@@ -306,6 +301,19 @@ gen_kernel() {
 		set_machine_id "$machine_id"
 		cat "$input"
 	} >"$output"
+}
+
+gen_preboot() {
+	PRESTUBDIRS="/etc/flash-kernel/preboot.d /usr/share/flash-kernel/preboot.d"
+	PRESTUBS="$(find $PRESTUBDIRS -type f -regex '.*/[0-9a-zA-Z_-]+' -printf '%f\n' | LC_ALL=C sort -u)"
+	for file in $PRESTUBS; do
+		for dir in $PRESTUBDIRS; do
+			if [ -f $dir/$file ]; then
+				cat $dir/$file
+				break
+			fi
+		done
+	done
 }
 
 gen_ubootenv() {
@@ -434,11 +442,11 @@ compress_type() {
 }
 
 get_kernel_cmdline() {
-        . /etc/default/flash-kernel
+        . ${FK_DEFAULTS}
 	echo "$LINUX_KERNEL_CMDLINE"
 }
 get_kernel_cmdline_defaults() {
-        . /etc/default/flash-kernel
+        . ${FK_DEFAULTS}
 	echo "$LINUX_KERNEL_CMDLINE_DEFAULTS"
 }
 
@@ -476,10 +484,12 @@ mkimage_script() {
 	local sdata="$3"
 	local script="$4"
 
-	local tdata="$tmpdir/$(basename $sdata)"
+	local tdata="$tmpdir/$(basename $sdata).out"
 
 	local ubootenv="$(mktemp --tmpdir=$tmpdir)"
 	gen_ubootenv > $ubootenv
+	local preboot="$(mktemp --tmpdir=$tmpdir)"
+	gen_preboot > $preboot
 
 	if [ "$(stat --printf='%s' $ubootenv)" -gt 0 ] && \
 		! grep -q '@@UBOOT_ENV_EXTRA@@' "$sdata" ; then
@@ -493,6 +503,10 @@ mkimage_script() {
             -e "/@@UBOOT_ENV_EXTRA@@/{
                   s/@@UBOOT_ENV_EXTRA@@//g
                   r $ubootenv
+                }" \
+            -e "/@@UBOOT_PREBOOT_EXTRA@@/{
+                  s/@@UBOOT_PREBOOT_EXTRA@@//g
+                  r $preboot
                 }" < $sdata > $tdata
 	mkimage -A "$mkarch" -O linux -T script -C none -a "$saddr" -e "$saddr" \
 		-n "$sdesc" -d "$tdata" "$script" >&2 1>/dev/null
@@ -512,22 +526,9 @@ mkimage_multi() {
 	echo "done." >&2
 }
 
-mkimage_env() {
-	local esize="$1"
-	local edata="$2"
-	local escript="$3"
-
-	# FIXME: should leverage gen_ubootenv
-	printf "Generating u-boot environment image... " >&2
-	mkenvimage -r -s "$esize" -o "$escript" "$edata"
-	echo "done." >&2
-
-
-}
-
 # Return a nonempty string *unless* NO_CREATE_DOT_BAK_FILES is set.
 get_dot_bak_preference() {
-	. /etc/default/flash-kernel
+	. ${FK_DEFAULTS}
 	case $(echo "$NO_CREATE_DOT_BAK_FILES" | tr '[:upper:]' '[:lower:]') in
 	    true|yes|1) ;;
 	    *) echo yes ;;
@@ -536,7 +537,7 @@ get_dot_bak_preference() {
 
 # Return a nonempty string *unless* MTD_BACKUP_DIR is "none".
 get_mtd_backup_dir() {
-	. /etc/default/flash-kernel
+	. ${FK_DEFAULTS}
 	case "${MTD_BACKUP_DIR:=/var/backups/flash-kernel}" in
 	    none) echo "";;
 	    *) echo "${MTD_BACKUP_DIR}";;
@@ -585,7 +586,6 @@ nslu2_swap() {
 	fi
 }
 
-# XXX needs testsuite coverage
 abootimg_get_image_size() {
 	local abootimg="$1"
 
@@ -596,7 +596,6 @@ dtb_append_required() {
 	linux-version compare "$kvers" ge "$dtb_append_from"
 }
 
-# XXX needs testsuite coverage
 android_flash() {
 	local device="$1"
 
@@ -616,10 +615,10 @@ include_only_flavors() {
 	# include_only_flavors(flav1, flav2, flav3)
 	# filter lines of input in uname -r format (X.Y.Z-N-flavor)
 	# and filter-out anything that is not in the listed input
-	# if exactly zero flavors are given, then assume everything is a match
+	# if the only flavor given is "any", then assume everything is a match
 	local cur_uname cur_flav allowed_flav
 	while read cur_uname; do
-		if [ $# -eq 0 ]; then
+		if [ "$*" = "any" ]; then
 			echo "$cur_uname"
 		else
 			# could use cur_flav=$(get_kfile_suffix "$cur_uname")
@@ -637,9 +636,9 @@ include_only_flavors() {
 
 find_dtb_file() {
 	local dtb path
-	case "$dtb_name" in
+	case "$dtb_dir" in
 	/*)
-		dtb="$dtb_name"
+		dtb="$dtb_dir/$dtb_name"
 		if [ ! -f "$dtb" ]; then
 			error "Couldn't find $dtb"
 		fi
@@ -647,7 +646,7 @@ find_dtb_file() {
 	*)
 		dtb=
 		paths="/etc/flash-kernel/dtbs /usr/lib/linux-image-$kvers /lib/firmware/$kvers/device-tree/"
-                for path in $paths; do
+		for path in $paths; do
 			dtb=$(find $path -name $dtb_name 2>/dev/null | head -n 1)
 			[ -z "$dtb" ] || break
 		done
@@ -659,14 +658,38 @@ find_dtb_file() {
 	echo $dtb
 }
 
+unique_filenames() {
+	awk '
+	{
+		file=$0;
+		sub("^.*/", "", file);
+		if (!(file in files)) files[file]=$0;
+	}
+	END {
+		for (file in files) print files[file];
+	}'
+}
+
+find_all_dtbs() {
+	# NOTE: The following assumes that "find" processes and outputs
+	# filenames in the same order as starting points ($paths) are specified
+	paths="/etc/flash-kernel/dtbs /usr/lib/linux-image-$kvers /lib/firmware/$kvers/device-tree/"
+	find $paths -name "*.dtb" 2>/dev/null | unique_filenames
+}
+
+find_all_overlays() {
+	paths="/etc/flash-kernel/dtbs /usr/lib/linux-image-$kvers /lib/firmware/$kvers/device-tree/"
+	find $paths -name "*.dtbo" 2>/dev/null | unique_filenames
+}
+
 handle_dtb() {
 	if [ "x$dtb_name" = "x" ]; then
 		return
 	fi
 
-	local dtb_name=$(basename "$dtb_name")
+	local dtb
 	if [ "x$FK_KERNEL_HOOK_SCRIPT" = "xpostrm.d" ] ; then
-		rm -f "/boot/dtbs/$kvers/$dtb_name"
+		rm -f "/boot/dtbs/$kvers/$dtb_dir/$dtb_name"
 
 		# This was the old name we installed under. We
 		# currently include it as an alternative symlink.
@@ -690,22 +713,26 @@ handle_dtb() {
 		fi
 	else
 		local dtb=$(find_dtb_file)
-		echo "Installing $dtb into /boot/dtbs/$kvers/$dtb_name" >&2
-		mkdir -p /boot/dtbs/$kvers/
-		cp "$dtb" "/boot/dtbs/$kvers/$dtb_name.new"
+		echo "Installing $dtb into /boot/dtbs/$kvers/$dtb_dir/$dtb_name" >&2
+		mkdir -p "/boot/dtbs/$kvers/$dtb_dir"
+		cp "$dtb" "/boot/dtbs/$kvers/$dtb_dir/$dtb_name.new"
 		backup_and_install \
-			"/boot/dtbs/$kvers/$dtb_name.new" \
-			"/boot/dtbs/$kvers/$dtb_name"
+			"/boot/dtbs/$kvers/$dtb_dir/$dtb_name.new" \
+			"/boot/dtbs/$kvers/$dtb_dir/$dtb_name"
+
+		if [ "$dtb_dir" != "." ]; then
+			ln -nfs "$dtb_dir/$dtb_name" "/boot/dtbs/$kvers/$dtb_name"
+		fi
 
 		# Historically we installed the dtb as
 		# dtb-$kvers, keep it around as an alternative
 		# for now. Useful for platforms which do not
 		# set ${fdtfile}
-		ln -nfs "dtbs/$kvers/$dtb_name" "/boot/dtb-$kvers"
+		ln -nfs "dtbs/$kvers/$dtb_dir/$dtb_name" "/boot/dtb-$kvers"
 
 		# This can be used along with the unversioned
 		# vmlinuz+initrd.gz e.g. as a fallback option
-		ln -nfs "dtbs/$kvers/$dtb_name" "/boot/dtb"
+		ln -nfs "dtbs/$kvers/$dtb_dir/$dtb_name" "/boot/dtb"
 	fi
 }
 
@@ -745,7 +772,10 @@ if [ -n "$kvers" ] ; then
 fi
 
 # if get_machine_field returns non-zero, then all flavors are allowed
-kflavors="$(get_machine_field "$machine" "Kernel-Flavors")" || :
+if ! kflavors=$(get_machine_field "$machine" "Kernel-Flavors") ; then
+	# Since no Kernel-Flavors were specified, allow any kernel.
+	kflavors="any"
+fi
 latest_version=$(linux-version list | include_only_flavors $kflavors | linux-version sort | tail -1)
 
 if [ -n "$kvers" ] && [ "$FK_KERNEL_HOOK_SCRIPT" = "postrm.d" ]; then
@@ -800,18 +830,9 @@ desc="kernel $kvers"
 idesc="ramdisk $kvers"
 
 if [ ! -e $kfile ] || [ ! -e $ifile ]; then
-	# installation-report #781742 included:
-	#     Can't find /boot/vmlinuz-[...] or /boot/initrd.img-[...]
-	#
-	# It's unclear how this can have happened or what state the
-	# system was in, so log some additional information in the
-	# hopes of catching it in the act next time.
-	(
-		set -x
-		ls -l $kfile*
-		ls -l $ifile*
-	) >> /tmp/flash-kernel-no-kernel-error.log 2>&1
-	error "Can't find $kfile or $ifile (see /tmp/flash-kernel-no-kernel-error.log)"
+	# See debian bug #781742 and LP: #1861292
+	echo "flash-kernel: $kfile or $ifile missing; expecting future run" >&2
+	exit 0
 fi
 kfilesize=$(stat -c '%s' "$kfile")
 ifilesize=$(stat -c '%s' "$ifile")
@@ -830,7 +851,7 @@ if ! check_supported "$machine"; then
 fi
 
 kfile_suffix=""
-for kflavor in ${kflavors:-"any"} ; do
+for kflavor in $kflavors ; do
 	if check_kflavors "$kvers" "$kflavor" ; then
 		kfile_suffix="$kflavor"
 		break
@@ -849,7 +870,6 @@ machine_id="$(get_machine_field "$machine" "Machine-Id")" || :
 method="$(get_machine_field "$machine" "Method")" || method="generic"
 mtd_kernel="$(get_machine_field "$machine" "Mtd-Kernel")" || :
 mtd_initrd="$(get_machine_field "$machine" "Mtd-Initrd")" || :
-dtb_kver="$(get_machine_field "$machine" "DTB-Kernel-Version")" || :
 dtb_append="$(get_machine_field "$machine" "DTB-Append")" || :
 dtb_append_from="$(get_machine_field "$machine" "DTB-Append-From")" || :
 ukaddr="$(get_machine_field "$machine" "U-Boot-Kernel-Address")" || :
@@ -858,14 +878,14 @@ uiaddr="$(get_machine_field "$machine" "U-Boot-Initrd-Address")" || :
 umaddr="$(get_machine_field "$machine" "U-Boot-Multi-Address")" || :
 usaddr="$(get_machine_field "$machine" "U-Boot-Script-Address")" || :
 usname="$(get_machine_field "$machine" "U-Boot-Script-Name")" || :
-# FIXME: currently hard coded because only RPi2 uses this; let's not define
-# new fields without consulting with Debian.
-ussize=16384
 boot_device="$(get_machine_field "$machine" "Boot-Device")" || :
 boot_kernel_path="$(get_machine_field "$machine" "Boot-Kernel-Path")" || :
 boot_initrd_path="$(get_machine_field "$machine" "Boot-Initrd-Path")" || :
+boot_kernel_path_version="$(get_machine_field "$machine" "Boot-Kernel-Path-Version")" || :
+boot_initrd_path_version="$(get_machine_field "$machine" "Boot-Initrd-Path-Version")" || :
 boot_script_path="$(get_machine_field "$machine" "Boot-Script-Path")" || :
 boot_dtb_path="$(get_machine_field "$machine" "Boot-DTB-Path")" || :
+boot_dtb_path_version="$(get_machine_field "$machine" "Boot-DTB-Path-Version")" || :
 boot_multi_path="$(get_machine_field "$machine" "Boot-Multi-Path")" || :
 android_boot_device="$(get_machine_field "$machine" "Android-Boot-Device")" || :
 android_skip_initrd="$(get_machine_field "$machine" "Android-Skip-Initrd")" || :
@@ -955,17 +975,6 @@ case "$method" in
 			gen_kernel "$kernel" "$tmpdir/kernel" "$machine_id"
 			kernel="$tmpdir/kernel"
 		fi
-		if [ -n "$dtb_kver" ]; then
-			if dpkg --compare-versions "$kvers" ge "$dtb_kver" >/dev/null; then
-				dtb="$(find /lib/firmware/$kvers/device-tree/ -name $dtb_name)"
-				if [ ! -f "$dtb" ] ; then
-					error "Couldn't find $dtb"
-				fi
-				append_dtb "$kernel" "$dtb" "$tmpdir/kernel.dtb"
-				mv "$tmpdir/kernel.dtb" "$tmpdir/kernel"
-				kernel="$tmpdir/kernel"
-			fi
-		fi
 		if [ -n "$ukaddr" ]; then
 			if [ -n "$ukepoint" ]; then
 				mkimage_kernel "$ukaddr" "$ukepoint" "$desc" "$kernel" \
@@ -992,6 +1001,9 @@ case "$method" in
 		fi
 		if [ -n "$boot_kernel_path" ]; then
 			boot_kernel_path="$boot_mnt_dir/$boot_kernel_path"
+			if [ "$boot_kernel_path_version" = "yes" ]; then
+			   boot_kernel_path="${boot_kernel_path}-${kvers}"
+			fi
 			# don't mv the original kernel
 			if [ "$kernel" = "$kfile" ]; then
 				cp "$kernel" "$tmpdir/kernel"
@@ -1001,14 +1013,6 @@ case "$method" in
 		elif [ -n "$kmtd" ]; then
 			flash_kernel "$tmpdir/uImage" "$kmtd" ""
 			rm -f "$tmpdir/uImage"
-		fi
-		if [ -n "$dtb_name" ] && [ -n "$boot_dtb_path" ]; then
-			dtb="$(find /lib/firmware/$kvers/device-tree/ -name $dtb_name)"
-			if [ -f "$dtb" ]; then
-				cp "$dtb" "$tmpdir/$dtb_name"
-				dtb_path="$boot_mnt_dir/$boot_dtb_path"
-				backup_and_install "$tmpdir/$dtb_name" "$dtb_path"
-			fi
 		fi
 		if [ -n "$boot_multi_path" ]; then
 			backup_and_install "$tmpdir/uImage" "$boot_multi_path"
@@ -1020,6 +1024,9 @@ case "$method" in
 		fi
 		if [ -n "$boot_initrd_path" ]; then
 			boot_initrd_path="$boot_mnt_dir/$boot_initrd_path"
+			if [ "$boot_initrd_path_version" = "yes" ]; then
+			   boot_initrd_path="${boot_initrd_path}-${kvers}"
+			fi
 			# don't mv the original initrd
 			if [ "$initrd" = "$ifile" ]; then
 				cp "$initrd" "$tmpdir/initrd"
@@ -1039,18 +1046,14 @@ case "$method" in
 			case $usname in
 				bootscr*)
 					boot_script_path="$boot_mnt_dir/$boot_script_path"
-					boot_script="$BOOTSCRIPTS_DIR/$usname"
+					boot_script="$tmpdir/bootscript"
+					for script in $usname ; do
+						echo "\n#\n# flash-kernel: $script\n#\n" >> "$boot_script"
+						cat "$BOOTSCRIPTS_DIR/$script" >> "$boot_script"
+					done
 					mkimage_script "$usaddr" "boot script" "$boot_script" \
 						"$tmpdir/boot.scr"
 					boot_script="$tmpdir/boot.scr"
-					backup_and_install "$boot_script" "$boot_script_path"
-				;;
-				uboot.env*)
-					boot_script_path="$boot_mnt_dir/$boot_script_path"
-					boot_script="$BOOTSCRIPTS_DIR/$usname"
-					mkimage_env "$ussize" "$boot_script" \
-						"$tmpdir/uboot.env"
-					boot_script="$tmpdir/uboot.env"
 					backup_and_install "$boot_script" "$boot_script_path"
 				;;
 				uEnvtxt*)
@@ -1073,11 +1076,46 @@ case "$method" in
 		fi
 		if [ -n "$boot_dtb_path" ] && [ "$dtb_append" != "no" ]; then
 			boot_dtb_path="$boot_mnt_dir/$boot_dtb_path"
+			if [ "$boot_dtb_path_version" = "yes" ]; then
+				boot_dtb_path="${boot_dtb_path}-${kvers}"
+			fi
 			boot_dtb=$(find_dtb_file)
 			dtb="$tmpdir/dtb"
 			cp "$boot_dtb" "$dtb"
 			backup_and_install "$dtb" "$boot_dtb_path"
 		fi
+	;;
+	"pi")
+		boot_dir="/boot/firmware"
+		boot_kernel_path=${boot_kernel_path:-$boot_dir/vmlinuz}
+		boot_initrd_path=${boot_initrd_path:-$boot_dir/initrd.img}
+		boot_script_path=${boot_script_path:-$boot_dir/boot.scr}
+		cp "$kfile" "$tmpdir/vmlinuz"
+		backup_and_install "$tmpdir/vmlinuz" "$boot_kernel_path"
+		cp "$ifile" "$tmpdir/initrd.img"
+		backup_and_install "$tmpdir/initrd.img" "$boot_initrd_path"
+		boot_script="$tmpdir/boot.scr"
+		for script in $usname ; do
+			echo "\n#\n# flash-kernel: $script\n#\n" >> "$boot_script"
+			cat "$BOOTSCRIPTS_DIR/$script" >> "$boot_script"
+		done
+		mkimage_script "$usaddr" "boot script" "$boot_script" "$tmpdir/boot.scr"
+		backup_and_install "$boot_script" "$boot_dir/boot.scr"
+		find_all_dtbs | {
+			while read dtb; do
+				dtb_name=$(basename $dtb)
+				cp "$dtb" "$tmpdir/$dtb_name"
+				backup_and_install "$tmpdir/$dtb_name" "$boot_dir/$dtb_name"
+			done
+		}
+		mkdir -p "$boot_dir/overlays"
+		find_all_overlays | {
+			while read overlay; do
+				overlay_name=$(basename $overlay)
+				cp "$overlay" "$tmpdir/$overlay_name"
+				backup_and_install "$tmpdir/$overlay_name" "$boot_dir/overlays/$overlay_name"
+			done
+		}
 	;;
 	"symlink")
 		rm -f /boot/initrd /boot/zImage
diff --git a/d-i/source/flash-kernel/test_functions b/d-i/source/flash-kernel/test_functions
--- a/d-i/source/flash-kernel/test_functions
+++ b/d-i/source/flash-kernel/test_functions
@@ -571,29 +571,28 @@ _test_mkimage_kernel() {
         . "$functions"
         saved_args=""
         mkarch="arm"
-        mkimage_kernel "0xdeadbeef" "0xbaddcafe" "desc" "input" "output" 2>/dev/null
-        expected="-A arm -O linux -T kernel -C none -a 0xdeadbeef -e 0xbaddcafe -n desc -d input output"
+        mkimage_kernel "0xdeadbeef" "0xbaddcafe" "desc" "$kdata" "output" 2>/dev/null
         if [ "$expected" != "$saved_args" ]; then
             echo "Expected mkimage_kernel to be called with \"$expected\" but it was called with \"$saved_args\"" >&2
-            return 1
+            exit 1
         fi
     )
 }
 
 test_mkimage_kernel() {
     local kdata="/dev/zero"
-    local expected="-A arm -O linux -T kernel -C none -a 0xdeadbeef -e 0xdeadbeef -n desc -d $kdata output"
-    _test_mkimage_kernel "$kdata" "$expected" || exit 1
+    local expected="-A arm -O linux -T kernel -C none -a 0xdeadbeef -e 0xbaddcafe -n desc -d $kdata output"
+    _test_mkimage_kernel "$kdata" "$expected"
 }
 add_test test_mkimage_kernel
 
 test_mkimage_kernel_gzip() {
-    local kdata="$(mktemp)"
+    get_tempfile
+    local kdata="$last_tempfile"
     gzip < /dev/null > "$kdata"
 
-    local expected="-A arm -O linux -T kernel -C gzip -a 0xdeadbeef -e 0xdeadbeef -n desc -d $kdata output"
-    _test_mkimage_kernel "$kdata" "$expected" || exit 1
-    rm -f "$kdata"
+    local expected="-A arm -O linux -T kernel -C gzip -a 0xdeadbeef -e 0xbaddcafe -n desc -d $kdata output"
+    _test_mkimage_kernel "$kdata" "$expected"
 }
 add_test test_mkimage_kernel_gzip
 
@@ -614,6 +613,60 @@ test_mkimage_initrd() {
     )
 }
 add_test test_mkimage_initrd
+
+test_mkimage_script() {
+    get_tempfile
+    mock_fk_defaults="$last_tempfile"
+    cat >"$mock_fk_defaults" <<EOF
+LINUX_KERNEL_CMDLINE="baz quux"
+LINUX_KERNEL_CMDLINE_DEFAULTS="foo"
+EOF
+    get_tempfile
+    mock_script="$last_tempfile"
+    cat >"$mock_script" <<EOF
+setenv bootargs @@LINUX_KERNEL_CMDLINE_DEFAULTS@@ bar @@LINUX_KERNEL_CMDLINE@@
+@@UBOOT_ENV_EXTRA@@
+bar
+@@UBOOT_PREBOOT_EXTRA@@
+end
+EOF
+    (
+        mkimage() {
+            saved_args="$@"
+            shift 15
+            generated_script="$(cat $1)"
+        }
+        . "$functions"
+        # Duplicate (some of) cleanups and tmpdir from main()
+        cleanups() {
+            rm -rf "$tmpdir"
+        }
+        trap cleanups EXIT HUP INT QUIT ILL KILL SEGV PIPE TERM
+        tmpdir="$(mktemp -dt "test_mkimage_script.XXXXXXXX")"
+        gen_ubootenv() {
+            echo foo
+        }
+        gen_preboot() {
+            echo baz
+        }
+        FK_DEFAULTS=$mock_fk_defaults
+        saved_args=""
+        generated_script=""
+        mkarch="arm"
+        mkimage_script "0xdeadbeef" "desc" "$mock_script" "script" 2>/dev/null
+        expected="-A arm -O linux -T script -C none -a 0xdeadbeef -e 0xdeadbeef -n desc -d $tmpdir/$(basename $mock_script).out script"
+        expected_script="$(printf "setenv bootargs foo bar baz quux\n\nfoo\nbar\n\nbaz\nend")"
+        if [ "$expected" != "$saved_args" ]; then
+            echo "Expected mkimage_script to be called with \"$expected\" but it was called with \"$saved_args\"" >&2
+            exit 1
+        fi
+        if [ "$generated_script" != "$expected_script" ]; then
+            echo "The script generated by mkimage_script did not match the expected output" >&2
+            exit 1
+        fi
+    )
+}
+add_test test_mkimage_script
 
 test_mkimage_multi() {
     (
@@ -706,6 +759,123 @@ test_dtb_append_from() {
     )
 }
 add_test test_dtb_append_from
+
+test_abootimg_get_image_size() {
+    abootimg_output="
+
+Android Boot Image Info:
+
+* file name = boot.img
+
+* image size = 8388608 bytes (8.00 MB)
+  page size  = 2048 bytes
+
+* Boot Name = \"\"
+
+* kernel size       = 3002744 bytes (2.86 MB)
+  ramdisk size      = 1639626 bytes (1.56 MB)
+
+* load addresses:
+  kernel:       0x10008000
+  ramdisk:      0x11000000
+  tags:         0x10000100
+
+* cmdline = mem=448M@0M nvmem=64M@448M vmalloc=320M video=tegrafb console=tty0 usbcore.old_scheme_first=1 quiet splash elevator=noop tegraboot=sdmmc cmdpart=1:7168:10240,2:17408:16384,3:35840:614400,4:4004864:27096064
+
+* id = 0x07571070 0x13950a6a 0x185c996f 0x9ab7b64d 0xcccd09bd 0x00000000 0x00000000 0x00000000
+"
+    (
+        . "$functions"
+        size=$(abootimg_get_image_size "$abootimg_output")
+        if [ "$size" -ne 8388608 ]; then
+            echo "Expected 8388608 but got $size" >&2
+            exit 1
+        fi
+    )
+}
+add_test test_abootimg_get_image_size
+
+test_android_flash() {
+    (
+        abootimg() {
+            saved_args="$@"
+        }
+        . "$functions"
+        saved_args=""
+        kfile="vmlinuz"
+        ifile="initrd.img"
+        android_flash /dev/some-dev 2>/dev/null
+        expected="-u /dev/some-dev -k vmlinuz -r initrd.img"
+        if [ "$expected" != "$saved_args" ]; then
+            echo "Expected abootimg to be called with \"$expected\" but it was called with \"$saved_args\"" >&2
+            exit 1
+        fi
+        saved_args=""
+        android_skip_initrd=1 android_flash /dev/some-dev 2>/dev/null
+        expected="-u /dev/some-dev -k vmlinuz"
+        if [ "$expected" != "$saved_args" ]; then
+            echo "Expected abootimg to be called with \"$expected\" but it was called with \"$saved_args\"" >&2
+            exit 1
+        fi
+    )
+}
+add_test test_android_flash
+
+test_find_all_dtbs() {
+    kvers="3.14"
+    get_tempfile
+    mock_find_output="$last_tempfile"
+    cat >"$mock_find_output" <<EOF
+/etc/flash-kernel/dtbs/bcm2709-rpi-2-b.dtb
+/lib/firmware/$kvers/device-tree/broadcom/bcm2709-rpi-2-b.dtb
+/lib/firmware/$kvers/device-tree/broadcom/bcm2710-rpi-3-b.dtb
+/lib/firmware/$kvers/device-tree/broadcom/bcm2711-rpi-4-b.dtb
+EOF
+    (
+        find() {
+            saved_args="$@"
+            cat "$mock_find_output"
+        }
+        . "$functions"
+        expected="\
+/etc/flash-kernel/dtbs/bcm2709-rpi-2-b.dtb
+/lib/firmware/$kvers/device-tree/broadcom/bcm2710-rpi-3-b.dtb
+/lib/firmware/$kvers/device-tree/broadcom/bcm2711-rpi-4-b.dtb"
+        if [ "$(find_all_dtbs | sort)" != "$expected" ]; then
+            echo "find_all_dtbs did not output the expected list of files" >&2
+            exit 1
+        fi
+    )
+}
+add_test test_find_all_dtbs
+
+test_find_all_overlays() {
+    kvers="3.14"
+    get_tempfile
+    mock_find_output="$last_tempfile"
+    cat >"$mock_find_output" <<EOF
+/etc/flash-kernel/dtbs/pi3-disable-bt.dtbo
+/lib/firmware/$kvers/device-tree/overlays/i2c0.dtbo
+/lib/firmware/$kvers/device-tree/overlays/vc4-fkms-v3d.dtbo
+/lib/firmware/$kvers/device-tree/overlays/pi3-disable-bt.dtbo
+EOF
+    (
+        find() {
+            saved_args="$@"
+            cat "$mock_find_output"
+        }
+        . "$functions"
+        expected="\
+/etc/flash-kernel/dtbs/pi3-disable-bt.dtbo
+/lib/firmware/$kvers/device-tree/overlays/i2c0.dtbo
+/lib/firmware/$kvers/device-tree/overlays/vc4-fkms-v3d.dtbo"
+        if [ "$(find_all_overlays | sort)" != "$expected" ]; then
+            echo "find_all_overlays did not output the expected list of files" >&2
+            exit 1
+        fi
+    )
+}
+add_test test_find_all_overlays
 
 test_main
 
